name: Documentation Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: |
          uv sync

      - name: Build documentation
        run: just build-docs

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/
          retention-days: 7

      - name: Check for broken links (optional)
        continue-on-error: true
        run: |
          # Check that key files were generated
          test -f docs/index.html || exit 1
          test -d docs/_static/marimo || exit 1
          echo "Documentation build validation passed!"
